ジャンケンapp を作りました
jumpei-1201/mobile_issue pull request #2
Opened 2020-05-06 11:37 UTC by jumpei-1201

2020-05-07 05:08 UTC, mcz9mm requested changes
コメントしました
Timerを利用しなくても実現できるので使わない方向で大丈夫です。

ジャンケン結果を表示し終わって自動で再度ゲームを始めるようにしたいのであれば遅延を使うと良いと思います。
https://qiita.com/koogawa/items/f6e8f31ca549dbf55e83

2020-05-07 05:08 UTC, mcz9mm commented on jankena_app/jankena_app/ViewController.swift
> +        switch you {
すまん、課題2で指摘するべきだったけど、ジャンケンのロジックをここのリンクを参考に直してみて。
https://staku.designbits.jp/check-janken/

2020-05-07 05:08 UTC, mcz9mm commented on jankena_app/jankena_app/ViewController.swift
> +        enemy.startAnimating()
なるほどね、こいつ使ったのね！
Timerじゃなくても同じことできるし良いと思う！
https://developer.apple.com/documentation/uikit/uiimageview/1621061-startanimating

2020-05-07 05:08 UTC, mcz9mm commented on jankena_app/jankena_app/ViewController.swift
> +
クラス内変数で良いと思う。毎回メソッドを呼ぶたびにインスタンスを生成してるのでメモリ効率悪いかと
let image1 = UIImage(named:"gu")!
let image2 = UIImage(named:"choki")!
let image3 = UIImage(named:"pa")!

2020-05-07 05:08 UTC, mcz9mm commented on jankena_app/jankena_app/ViewController.swift
> +
UIImageやUIColorはリテラルの補完ができます。

```
    let rock = #imageLiteral(resourceName: "gu")
    let scissors = #imageLiteral(resourceName: "choki")
    let paper = #imageLiteral(resourceName: "pa")
```
![スクリーンショット 2020-05-07 13 58 09](https://user-images.githubusercontent.com/11751495/81256233-ca1c3200-906a-11ea-86e3-0ac4b751447d.png)

参考：
https://dev.classmethod.jp/articles/xcode-8-image-and-color-literals/

2020-05-07 05:08 UTC, mcz9mm commented on jankena_app/jankena_app/ViewController.swift
> +        let image1 = UIImage(named:"gu")!
image1,2,3 などはマジック変数(マジックナンバー)と呼ばれ、可読性が悪く不具合を生む原因になります。
極力変数名は具体的な名前にすると良いでしょう。

`let image1 = UIImage(named:"gu")!`
↓
`let rockImage = UIImage(named:"gu")!`

2020-05-07 05:08 UTC, mcz9mm commented on jankena_app/jankena_app/ViewController.swift
> +        let imageListArray :Array<UIImage> = [image1, image2, image3]
` let imageListArray :[UIImage] = [image1, image2, image3]`
もしくは、
`let imageListArray = [image1, image2, image3]`

Swiftには型推論があるので

2020-05-07 05:08 UTC, mcz9mm commented on jankena_app/jankena_app/ViewController.swift
> +        viewDidLoad().self
ViewDidLoadを再度呼ぶのはライフサイクル的におかしいので別のメソッドに切り出してあげれば良いかと。

2020-05-07 05:08 UTC, mcz9mm commented on jankena_app/jankena_app/ViewController.swift
> +    enum Hand{
このenum利用してないよ、

2020-05-07 05:08 UTC, mcz9mm commented on jankena_app/jankena_app/ViewController.swift
> +    enum Result{
このenumも使ってない

2020-05-07 05:08 UTC, mcz9mm commented on jankena_app/jankena_app/ViewController.swift
> +        return nil
`nil`を返すなら戻り値なしにすれば良いかと

`func janken( you:Hand ) {`

2020-05-07 05:09 UTC, mcz9mm commented on jankena_app/jankena_app/ViewController.swift
> +    enum Hand{
資料読んで
https://classroom.google.com/c/NzA1Nzc0Mzk4MDRa/m/Nzg1NDAzOTQyNDNa/details

2020-05-07 07:40 UTC, jumpei-1201 commented on jankena_app/jankena_app/ViewController.swift
> +        switch you {
playground の方でも変更してロジックを作り直しました！

2020-05-07 07:42 UTC, jumpei-1201 commented on jankena_app/jankena_app/ViewController.swift
> +
なるほど！ありがとうございます！リテラルはめちゃくちゃ便利ですね😂
list は呼び出すごとに生成していますが大丈夫ですか？

2020-05-07 07:42 UTC, jumpei-1201 commented on jankena_app/jankena_app/ViewController.swift
> +        let image1 = UIImage(named:"gu")!
わかりました！固有名詞で変数名を管理するように努めます！

2020-05-07 07:43 UTC, jumpei-1201 commented on jankena_app/jankena_app/ViewController.swift
> +        let imageListArray :Array<UIImage> = [image1, image2, image3]
array を無くして [UIImage] で変更しました

2020-05-07 07:44 UTC, jumpei-1201 commented on jankena_app/jankena_app/ViewController.swift
> +        viewDidLoad().self
遅延関数を載せていただいたのでそれをそのまま追加しました。

2020-05-07 07:46 UTC, jumpei-1201 commented on jankena_app/jankena_app/ViewController.swift
> +        return nil
戻り値なしの -> なしにすると警告も消えました。ありがとうございます。

2020-05-08 05:08 UTC, mcz9mm commented on janken.playground/Contents.swift
> +enum Hand: Int{
enumにはメソッドを追加できるので、selfで参照しcaseによって欲しい値を作成できるよ

```
enum Hand: Int {
        case rock = 0
        case scissors = 1
        case paper = 2

        func image() -> UIImage {
            switch self {
            case .rock: return #imageLiteral(resourceName: "gu")
            case .scissors: return #imageLiteral(resourceName: "choki")
            case .paper: return #imageLiteral(resourceName: "pa")
            }
        }
    }
```

Handのタイプを持った変数からこうやって値(UIImage)を取れるよ
```
enemy.image = pchand.image()
```

2020-05-08 05:08 UTC, mcz9mm commented on janken.playground/Contents.swift
> +    let pchand = hand[num_random]
自分だったらこうするかな、わざわざ配列作らなくても良い。
enumにはrawValue(Int)から生成できるので、

```
guard let pchand = Hand(rawValue: Int(arc4random_uniform(UInt32(3)))) else {
    return
}
```

2020-05-08 05:08 UTC, mcz9mm commented on janken.playground/Contents.swift
> +    let num_result = (you.rawValue - pchand.rawValue + 3) % 3
キャメルケースで `num_result `→ `numResult `

2020-05-08 05:08 UTC, mcz9mm commented on jankena_app/jankena_app/ViewController.swift
> +    @objc func animetion_start(_ timer:Timer) {
Timerは不要のはず！
アニメーション開始に必要な実装を呼び出すだけで良いよ。

```
func animetionStart() {
        enemy.animationImages = imageListArray
        enemy.animationDuration = 0.5
        enemy.startAnimating()
}
```

2020-05-08 05:08 UTC, mcz9mm commented on jankena_app/jankena_app/ViewController.swift
> +            self.resultLabel.text = "JANKEN..."
謎に"JANKEN..."を２回入れ直してるけど、、

遅延処理終了時にメソッドを切り分けると可読性が上がるはず
```
func reset() {
        resultLabel.text = "JANKEN..."
        animetionStart()
 }
```

2020-05-08 05:08 UTC, mcz9mm commented on jankena_app/jankena_app/ViewController.swift
> +
listもクラス変数に入れて構わないよ
`let imageListArray = [Hand.rock.image(), Hand.scissors.image(), Hand.paper.image()]`

2020-05-08 05:08 UTC, mcz9mm commented on jankena_app/jankena_app/ViewController.swift
> +        timer = Timer.scheduledTimer(timeInterval: 1.0, target: self, selector: #selector(self.animetion_start(_:)), userInfo: nil, repeats: false)
timerは不要で！

2020-05-08 05:17 UTC, mcz9mm reviewed
個人的、というか大体そうなんだけどメソッドなり変数の書く位置を決めておくと見やすいよ。

```
class ViewController: UIViewController {

    // IBOutlet系のクラス変数
    @IBOutlet weak var enemy: UIImageView!
    @IBOutlet weak var resultLabel: UILabel!

    // クラス変数
    var timer : Timer?
    var imageView:UIImageView!
    let imageListArray = [Hand.rock.image(), Hand.scissors.image(), Hand.paper.image()]

    enum Hand: Int {
    }

    enum Result: String {
    }
    
    // ViewControllerのライフサイクル系
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
    }
    
    // IBAction系
    @IBAction func gu(_ sender: Any) {
        janken(you: .rock)
    }

    @IBAction func choki(_ sender: Any) {
        janken(you: .scissors)
    }
    @IBAction func pa(_ sender: Any) {
        janken(you: .paper)
    }

　// 内部メソッド系
    func janken( you:Hand) {
    }

    func reset() {
    }
    
    func animetionStart() {
    }
}

```

2020-05-08 05:17 UTC, mcz9mm commented on jankena_app/jankena_app/ViewController.swift
> +        var pchandLabel = UIImage()
enumにメソッド作成すればここでの処理は不要になる

https://github.com/jumpei-1201/mobile_issue/pull/2/files#diff-635272396672d24b5d18ba6a6827b82bR7

2020-05-08 06:35 UTC, jumpei-1201 commented on janken.playground/Contents.swift
> +enum Hand: Int{
なるほど！Hand.image() をすることで戻り値が写真になるのですね！めちゃくちゃコードの量とみやすくなります！

2020-05-08 06:37 UTC, jumpei-1201 commented on janken.playground/Contents.swift
> +    let pchand = hand[num_random]
Hand の値を代入した方から使う方法が思いつかなかったので配列を作ってました、、
Hand( rawValue:  ) で取り出せるのですね！

2020-05-08 06:39 UTC, jumpei-1201 commented on janken.playground/Contents.swift
> +    let num_result = (you.rawValue - pchand.rawValue + 3) % 3
キャメルケースを使う時はOUTLETなどのImage, Label だけでなく result もするのですね。
animetion_start もした方がいいですか？

2020-05-08 06:39 UTC, jumpei-1201 commented on jankena_app/jankena_app/ViewController.swift
> +            self.resultLabel.text = "JANKEN..."
わかりました！

2020-05-08 06:41 UTC, jumpei-1201 commented on jankena_app/jankena_app/ViewController.swift
> +        var pchandLabel = UIImage()
enum だけで結構まとめられるのですね。一括りにしてるようであまり使いやすくないなと思っていたのですが、メソッドを入れると幅が広がりますね！なるほど。

2020-05-08 08:16 UTC, mcz9mm commented on janken.playground/Contents.swift
> +    let pchand = hand[num_random]
そうそう！
その発見大事よ、

2020-05-08 08:17 UTC, mcz9mm commented on janken.playground/Contents.swift
> +enum Hand: Int{
他の人が読んだとき、1ヶ月後の自分が読んだときに分かる内容だと良いね！

2020-05-08 08:19 UTC, mcz9mm commented
LGTM!
![](https://68.media.tumblr.com/60cdfc770d9601eae9236552bbd43242/tumblr_nzenhqSbIa1tjxt6ao1_400.gif)

2020-05-08 08:51 UTC, merged